export { default as Header } from "./Home/Header";
export { default as Sidebar } from "./Home/Sidebar";
export { default as Slider} from "./Home/Slider";
export { default as About} from "./Home/About";
export { default as SpeakerOne} from "./Home/SpeakerOne";
export { default as CounterOne} from "./Home/CounterOne";
export { default as FeatureOne} from "./Home/FeatureOne";
export { default as LeadershipOne} from "./Home/LeadershipOne";
export { default as GalleryOne} from "./Home/GalleryOne";
export { default as PriceOne} from "./Home/PriceOne";
export { default as VideoOne} from "./Home/VideoOne";
export { default as ClientOne} from "./Home/ClientOne";
export { default as NewsOne} from "./Home/NewsOne";
export { default as SubscribeOne } from "./Home/SubscribeOne";
export { default as Footer } from "./Home/Footer";
export { default as SearchPopup } from "./Home/SearchPopup";